
from typing import List, Tuple


class Syntax:
    name: str
    language: str


class SyntaxSet:
    languages: List[str] = ...

    def find_syntax_by_extension(self, extension: str) -> Syntax: ...


class Theme:
    name: str


class ThemeSet:
    themes: List[str]

    def __getitem__(self, theme: str) -> Theme: ...


class Color:
    r: int = ...
    g: int = ...
    b: int = ...
    a: int = ...


class Style:
    foreground: Color = ...
    background: Color = ...
    font_style: int = ...


def load_theme_folder(path: str) -> ThemeSet: ...
def load_syntax_folder(path: str) -> SyntaxSet: ...
def highlight(text: str, language: str, syntax_set: SyntaxSet,
              theme: Theme) -> List[Tuple[Style, str]]: ...
