
from typing import List, Tuple


class Color:
    r: int = ...
    g: int = ...
    b: int = ...
    a: int = ...


class Style:
    foreground: Color = ...
    background: Color = ...
    font_style: int = ...


def highlight(text: str, language: str) -> List[Tuple[Style, str]]: ...
