name: MacOS release

on:
    release:
      types:
        - created
jobs:
    linux:
        name: MacOS Py${{ matrix.PYTHON_VERSION }}
        runs-on: macos-latest
        env:
            PYTHON_VERSION: ${{ matrix.PYTHON_VERSION }}
            RUNNER_OS: "macos"
        strategy:
            fail-fast: false
            matrix:
                PYTHON_VERSION: ["3.6", "3.7", "3.8", "3.9"]
        steps:
            - name: Checkout branch
              uses: actions/checkout@v1
            - name: Install latest Rust nightly
              uses: actions-rs/toolchain@v1
              with:
                toolchain: stable
                override: true
                components: rustfmt, clippy
            - name: Print Rust version
              shell: bash -l {0}
              run: rustc --version
            - name: Install miniconda
              uses: conda-incubator/setup-miniconda@v2
              with:
                auto-update-conda: true
                activate-environment: test
                channels: conda-forge,defaults
                python-version: ${{ matrix.PYTHON_VERSION }}
            - name: Install build/test dependencies
              shell: bash -l {0}
              run: pip install maturin toml pytest
            - name: Build and publish pysyntect
              shell: bash -l {0}
              env:
                MATURIN_PASSWORD: ${{secrets.MATURIN_PASSWORD}}
                MATURIN_USERNAME: ${{secrets.MATURIN_USERNAME}}
              run: |
                SKIP_SDIST=$([ $PYTHON_VERSION == "3.9" -a $RUNNER_OS == "Linux" ] && echo "" || echo "--no-sdist")
                maturin publish -i $(which python) -u $MATURIN_USERNAME  $SKIP_SDIST
